name: Quality

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: [macos, self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - run: go test ./...

  lint:
    name: Lint
    runs-on: [macos, self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=5m

  vet:
    name: Vet
    runs-on: [macos, self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - run: go vet ./...
